### ISSUE TITLE
[US]: Créer un compte

### ISSUE THREAD

**Issue by Antoine3312** [IUT-Blagnac/sae3-01-devapp-g1a-2#7]
### User Story

En tant que futur client je souhaite pouvoir créer un compte sur Noskia afin de bénéficier de la meilleure expérience possible.

### Importance

Must

### Tâches associées

- [x] [Réaliser une maquette](https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/issues/8)
- [x] [Coder la page](https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/issues/9)
- [x] [Stockage BD](https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/issues/10)
- [x] [Tester le fonctionnement](https://github.com/IUT-Blagnac/sae3-01-devapp-g1a-2/issues/11)
